### PR TITLE
icon-changes

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
hover effect over the icons are changed with little change in background and icon colour

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
@Vac95 please review my PR

**Comment by 05hiteshbansal** [comment]
@shoaibsajid1 please review my PR

**Comment by 05hiteshbansal** [comment]
@ldelavois please review my PR

**Comment by 05hiteshbansal** [comment]
@mspronesti please review my PR

**Comment by 05hiteshbansal** [comment]
@Vac95 please review my PR

**Comment by 05hiteshbansal** [comment]
@shoaibsajid1 @ldelavois  please review and merge my PR

**Comment by ldelavois** [comment]
@05hiteshbansal can you show us some screenshots please?

**Comment by 05hiteshbansal** [comment]
https://github.com/soumyajit4419/Portfolio/assets/83907989/a8dc2f1a-b510-4de7-be78-fe61a8f850a0

here is the example

**Comment by 05hiteshbansal** [comment]
@ldelavois please have a look

**Comment by ldelavois** [comment]
@05hiteshbansal nice! It's ok for me but i can't push it

**Comment by 05hiteshbansal** [comment]
thanks for your appreciation

**Pull request closed without merging**
